# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: lint
        name: Linter
        entry: "scripts/lint-pre-commit.sh"
        language: python
        #        language_version: python3.12
        types: [python]
        require_serial: true
        verbose: true

  - repo: local
    hooks:
      - id: static-analysis
        name: Static analysis
        entry: "scripts/static-pre-commit.sh"
        language: python
        #        language_version: python3.12
        types: [python]
        require_serial: true
        verbose: true

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]

  - repo: local
    hooks:
      - id: check-registered-app
        name: Check if the app name is registered in fly.io
        entry: "scripts/check-registered-app-pre-commit.sh"
        language: python
        require_serial: true
        verbose: true
