version: '3'

services:
  # nosemgrep: yaml.docker-compose.security.writable-filesystem-service.writable-filesystem-service, yaml.docker-compose.security.no-new-privileges.no-new-privileges
  python-3.12-sukob:
    image: mcr.microsoft.com/devcontainers/python:3.12
    container_name: sukob-${USER}-python-3.12
    volumes:
      - ../:/workspaces/sukob:cached
    command: sleep infinity

    env_file:
      - ./devcontainer.env
    networks:
      - sukob-network

networks:
  sukob-network:
    name: sukob-${USER}-network
